//! Données de démonstration portées depuis `docs/Mockup.html`, corrigées pour Linux
//! (chemins binaires, interfaces réseau) et alignées sur le nom de chaîne nftables réel
//! `VITRAIL_REDIRECT`. Source unique partagée par les modules de `commands/` pour éviter
//! toute duplication — sera supprimé quand `correlation`/`storage` produiront les données
//! réelles (EPICs 1 à 7). Les flux mockés vivent dans `mock_flows.rs` (limite de 500 lignes).

use super::types::{DestinationInfo, FlowVisibility, ProcessInfo, SubsystemStatus};

pub fn processes() -> Vec<ProcessInfo> {
    vec![
        ProcessInfo {
            name: "Google Chrome".into(),
            path: "/usr/bin/google-chrome-stable".into(),
            pids: vec![4821, 4855],
            volume_mb: 148.3,
            destinations: 42,
            visibility: FlowVisibility::Fully,
            keylog_covered: true,
        },
        ProcessInfo {
            name: "Firefox".into(),
            path: "/usr/lib/firefox/firefox".into(),
            pids: vec![5102],
            volume_mb: 89.7,
            destinations: 31,
            visibility: FlowVisibility::Fully,
            keylog_covered: true,
        },
        ProcessInfo {
            name: "Slack".into(),
            path: "/usr/lib/slack/slack".into(),
            pids: vec![6234],
            volume_mb: 34.2,
            destinations: 8,
            visibility: FlowVisibility::Meta,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "Discord".into(),
            path: "/opt/discord/Discord".into(),
            pids: vec![6510],
            volume_mb: 67.8,
            destinations: 12,
            visibility: FlowVisibility::Meta,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "VS Code".into(),
            path: "/usr/share/code/code".into(),
            pids: vec![7201],
            volume_mb: 22.1,
            destinations: 15,
            visibility: FlowVisibility::Fully,
            keylog_covered: true,
        },
        ProcessInfo {
            name: "Spotify".into(),
            path: "/opt/spotify/spotify".into(),
            pids: vec![8100],
            volume_mb: 156.4,
            destinations: 6,
            visibility: FlowVisibility::Fully,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "Docker Desktop".into(),
            path: "/opt/docker-desktop/bin/docker-desktop".into(),
            pids: vec![3300],
            volume_mb: 445.2,
            destinations: 28,
            visibility: FlowVisibility::Attrib,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "Node.js".into(),
            path: "/usr/bin/node".into(),
            pids: vec![9100, 9120, 9155],
            volume_mb: 18.6,
            destinations: 9,
            visibility: FlowVisibility::Fully,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "curl".into(),
            path: "/usr/bin/curl".into(),
            pids: vec![10230],
            volume_mb: 0.4,
            destinations: 1,
            visibility: FlowVisibility::Attrib,
            keylog_covered: false,
        },
        ProcessInfo {
            name: "python3".into(),
            path: "/usr/bin/python3".into(),
            pids: vec![10400],
            volume_mb: 12.8,
            destinations: 5,
            visibility: FlowVisibility::Fully,
            keylog_covered: false,
        },
    ]
}

pub fn destinations() -> Vec<DestinationInfo> {
    vec![
        DestinationInfo {
            domain: "api.google.com".into(),
            ip: "142.250.74.238".into(),
            volume_mb: 87.3,
            process_count: 2,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:02:11".into(),
            last_seen: "14:58:44".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "cdn.jsdelivr.net".into(),
            ip: "151.101.1.229".into(),
            volume_mb: 45.2,
            process_count: 3,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:05:33".into(),
            last_seen: "14:57:01".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "github.com".into(),
            ip: "140.82.121.4".into(),
            volume_mb: 33.8,
            process_count: 2,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:08:22".into(),
            last_seen: "14:55:19".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "slack.com".into(),
            ip: "34.237.168.12".into(),
            volume_mb: 28.1,
            process_count: 1,
            visibility: FlowVisibility::Meta,
            tls: true,
            pinning: true,
            first_seen: "14:10:05".into(),
            last_seen: "14:58:30".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "discord.gg".into(),
            ip: "162.159.135.232".into(),
            volume_mb: 52.4,
            process_count: 1,
            visibility: FlowVisibility::Meta,
            tls: true,
            pinning: true,
            first_seen: "14:11:40".into(),
            last_seen: "14:58:50".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "spotify.com".into(),
            ip: "35.186.224.45".into(),
            volume_mb: 112.6,
            process_count: 1,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:03:18".into(),
            last_seen: "14:58:55".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "registry-1.docker.io".into(),
            ip: "52.5.133.89".into(),
            volume_mb: 312.7,
            process_count: 1,
            visibility: FlowVisibility::Attrib,
            tls: false,
            pinning: false,
            first_seen: "14:01:02".into(),
            last_seen: "14:56:33".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "crates.io".into(),
            ip: "18.214.128.42".into(),
            volume_mb: 8.4,
            process_count: 2,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:20:11".into(),
            last_seen: "14:45:22".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "fonts.googleapis.com".into(),
            ip: "142.250.74.238".into(),
            volume_mb: 2.1,
            process_count: 2,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:05:40".into(),
            last_seen: "14:30:15".into(),
            tag: None,
        },
        DestinationInfo {
            domain: "play.googleapis.com".into(),
            ip: "142.250.74.174".into(),
            volume_mb: 95.8,
            process_count: 1,
            visibility: FlowVisibility::Fully,
            tls: true,
            pinning: false,
            first_seen: "14:04:10".into(),
            last_seen: "14:58:40".into(),
            tag: None,
        },
    ]
}

pub fn subsystems(active: bool) -> Vec<SubsystemStatus> {
    let status = if active { "ok" } else { "off" };
    vec![
        SubsystemStatus {
            id: "opensnitch".into(),
            name: "Attribution (OpenSnitch)".into(),
            detail: "Daemon de corrélation processus/flux".into(),
            status: status.into(),
        },
        SubsystemStatus {
            id: "capture".into(),
            name: "Capture nftables".into(),
            detail: "Règles de redirection du trafic".into(),
            status: status.into(),
        },
        SubsystemStatus {
            id: "polarproxy".into(),
            name: "Décryptage (PolarProxy)".into(),
            detail: "Intercepteur TLS/MITM local".into(),
            status: status.into(),
        },
        SubsystemStatus {
            id: "keylog".into(),
            name: "Keylog SSLKEYLOGFILE".into(),
            detail: "Export de clés par les applications".into(),
            status: status.into(),
        },
        SubsystemStatus {
            id: "nftables".into(),
            name: "Règles nftables".into(),
            detail: "Chaîne VITRAIL_REDIRECT active".into(),
            status: status.into(),
        },
        SubsystemStatus {
            id: "ca".into(),
            name: "CA installée".into(),
            detail: "Certificat racine dans le trust store".into(),
            status: status.into(),
        },
    ]
}

pub const MONITORED_INTERFACES: [&str; 3] = ["wlan0", "wg0", "enp3s0"];
pub const NFTABLES_CHAIN: &str = "VITRAIL_REDIRECT";
